import React from 'react';
import {renderToString} from 'react-dom/server';
import assert from 'node:assert/strict';
import CoreModule,{AccountDetail,openingShopState,openingSubjectOptions,resizeOpeningRows} from './CoreModule.jsx';
import DataGraph from './DataGraph.jsx';
import {SubjectEditor,ShopEditor,SupplierEditor,DirectEditor} from './CoreFields.jsx';
import {freshState} from './model.js';
import seed from './realData.json';
const db=freshState(seed),session={role:'商务',name:'演示商务 A',businessId:'demo-sales-a'};
const p={db,session,params:{},update:()=>{},go:()=>{},toast:()=>{},openAccount:()=>{}};
for(const moduleId of ['M01','M02','M03','M04','M05','M06','M07','M08']){const html=renderToString(<CoreModule {...p} moduleId={moduleId}/>);assert.ok(html.length>100,moduleId);}
const subject=renderToString(<SubjectEditor {...p} customerId="1115" onSaved={()=>{}} onClose={()=>{}}/>);for(const field of ['统一社会信用代码','主体银行账号','联系人','联系电话','行业'])assert.ok(subject.includes(field),field);
const shop=renderToString(<ShopEditor {...p} subjectId="1389" product="本地推" onSaved={()=>{}} onClose={()=>{}}/>);assert.ok(shop.includes('店铺名称（来客名称）'));assert.ok(shop.includes('来客 ID'));assert.ok(!shop.includes('value="" aria-label="来客名称"'));
const supplier=renderToString(<SupplierEditor {...p} session={{role:'开户媒介'}} supplierId={db.suppliers[0].id} onClose={()=>{}}/>);assert.ok(supplier.includes('代理商 ID'));assert.ok(supplier.includes('供应商银行账号'));
const detail=renderToString(<AccountDetail {...p} accountId={db.accounts[0].id} onClose={()=>{}}/>);assert.ok(detail.includes(db.accounts[0].externalId));assert.ok(detail.includes('发起充值'));
const first=resizeOpeningRows([],1),three=resizeOpeningRows(first,3);
assert.equal(first.length,1);assert.equal(three.length,3);assert.equal(three[0].id,first[0].id);assert.equal(new Set(three.map(r=>r.id)).size,3);
assert.deepEqual(resizeOpeningRows(three,1),first);assert.equal(resizeOpeningRows(first,0).length,1);
const fixture=structuredClone(db),customerId=fixture.customers[0].id;
const zhiJi=openingSubjectOptions(db,'1082');
assert.deepEqual(zhiJi.linked.map(s=>s.id),['1560'],'选智集文化后空搜索必须列出其真实关联主体');
assert.equal(zhiJi.other.length,0,'空搜索不能把其他客户主体当作已关联资料');
const customerOnly=renderToString(<CoreModule {...p} moduleId="M06" params={{mode:'new',customerId:'1082'}}/>);
assert.ok(customerOnly.includes('大连鱿点酷文化传媒有限公司'));
assert.ok(customerOnly.replace(/<!--.*?-->/g,'').includes('该客户已关联主体（1）'));
assert.ok(customerOnly.includes('＋ 新增主体'),'空搜索仍有新增入口');
const selectedZhiJi=renderToString(<CoreModule {...p} moduleId="M06" params={{mode:'new',customerId:'1082',subjectId:'1560'}}/>);
assert.ok(selectedZhiJi.includes('已选择店铺'));
assert.ok(!selectedZhiJi.includes('新增店铺'),'已有唯一店不能另建第二店');
const unlinked=openingSubjectOptions(db,'1082','潮拍');
assert.equal(unlinked.linked.length,0);
assert.ok(unlinked.other.length>0,'全局已登记主体可查到但单独列为未关联');
assert.ok(unlinked.other.every(s=>!s.customerIds.includes('1082')));
assert.deepEqual(openingSubjectOptions(db,'').linked,[],'未选客户不展示其他主体');
fixture.customers.push({id:'customer-empty-ui',name:'空资料演示客户'});
const noSubject=renderToString(<CoreModule {...p} db={fixture} moduleId="M06" params={{mode:'new',customerId:'customer-empty-ui'}}/>);
assert.ok(noSubject.includes('该客户暂无关联主体'));
assert.ok(noSubject.includes('＋ 新增主体'));
for(let i=0;i<12;i++)fixture.subjects.push({id:'many-linked-'+i,name:'批量候选主体'+i,creditCode:'TEST-CODE-'+i,customerIds:['customer-empty-ui']});
const twelve=renderToString(<CoreModule {...p} db={fixture} moduleId="M06" params={{mode:'new',customerId:'customer-empty-ui'}}/>);
assert.ok(twelve.includes('批量候选主体11'),'关联列表不截断第11、12个主体');
assert.equal(openingSubjectOptions(fixture,'customer-empty-ui','TEST-CODE-11').linked[0].id,'many-linked-11');
const noShop=renderToString(<CoreModule {...p} db={fixture} moduleId="M06" params={{mode:'new',customerId:'customer-empty-ui',subjectId:'many-linked-0'}}/>);
assert.ok(noShop.includes('此主体尚未登记店铺'));
assert.ok(noShop.includes('新增店铺'));
fixture.subjects.push({id:'subject-ui-test',name:'主体直客统一名称',customerIds:[customerId],directId:'DEMO-SUBJECT-DIRECT',recordVersion:1});
fixture.shops.push({id:'shop-ui-test',subjectId:'subject-ui-test',name:'店铺与来客同名',laikeId:''});
assert.equal(openingShopState(fixture,'subject-ui-test').shop.id,'shop-ui-test');
const opening=renderToString(<CoreModule {...p} db={fixture} moduleId="M06" params={{mode:'new',customerId,subjectId:'subject-ui-test'}}/>);
for(const label of ['搜索客户名称','搜索主体名称或信用代码','客户与开户信息','主体与店铺资料','开户数量','营业执照与资质','店铺与来客同名','DEMO-SUBJECT-DIRECT'])assert.ok(opening.includes(label),label);
for(const obsolete of ['下一步','步骤 1 / 4','拟账户名称','意向供应商','查询 / 录入本行直客','按申请行绑定'])assert.ok(!opening.includes(obsolete),obsolete+' must be absent');
assert.match(opening,/aria-label="减少开户数量" disabled=""/);assert.match(opening,/<output aria-label="开户数量">1<\/output>/);
fixture.openingDraft={draftId:'draft-ui-test',customerId,subjectId:'subject-ui-test',shopId:'shop-ui-test',product:'本地推',region:'华南',businessOwnerId:session.businessId,rows:three,requestedCount:3,attachments:[]};
const draft=renderToString(<CoreModule {...p} db={fixture} moduleId="M06" params={{mode:'resumeDraft'}}/>);assert.match(draft,/<output aria-label="开户数量">3<\/output>/);
fixture.shops.push({id:'historical-second-shop',subjectId:'subject-ui-test',name:'另一个历史店铺'});
assert.equal(openingShopState(fixture,'subject-ui-test').shop,null);assert.equal(openingShopState(fixture,'subject-ui-test').conflict,true);
const conflict=renderToString(<CoreModule {...p} db={fixture} moduleId="M06" params={{mode:'new',customerId,subjectId:'subject-ui-test',shopId:'shop-ui-test'}}/>);
assert.ok(conflict.includes('历史关系待核对'));assert.ok(!conflict.includes('已自动带出主体唯一店铺'));assert.match(conflict,/disabled="">提交开户申请/);
fixture.shops.pop();
fixture.applications.push({id:'app-ui-test',customerId,subjectId:'subject-ui-test',shopId:'shop-ui-test',product:'本地推',region:'华南',workflowVersion:1,createdAt:new Date().toISOString(),businessOwnerName:session.name,status:'部分完成',assignee:'媒介',requestedCount:3,rows:three.map((r,i)=>({...r,status:i===0?'成功':'待办理',externalId:i===0?'DEMO-ACCOUNT-ID':'',accountId:i===0?'account-ui-test':undefined})),events:[],attachments:[],flowSnapshot:[],fieldSnapshot:[]});
const media=renderToString(<CoreModule {...p} db={fixture} session={{role:'开户媒介',name:'媒介'}} moduleId="M06" params={{applicationId:'app-ui-test'}}/>);
for(const label of ['申请数量','开户成功','待处理','开户账户明细','主体名称（直客名称）','DEMO-ACCOUNT-ID'])assert.ok(media.includes(label),label);
assert.ok(!media.includes('补全 / 编辑直客'));
const direct=renderToString(<DirectEditor {...p} db={fixture} subjectId="subject-ui-test" onClose={()=>{}}/>);assert.ok(direct.includes('主体直客统一名称'));assert.ok(direct.includes('DEMO-SUBJECT-DIRECT'));assert.match(direct,/readonly=""/i);
const graph=renderToString(<DataGraph db={fixture} customerId={customerId} openAccount={()=>{}}/>);assert.ok(graph.includes('主体直客：'));assert.ok(graph.includes('DEMO-SUBJECT-DIRECT'));assert.ok(!graph.includes('直客与纵横分别属于账户'));
console.log('Core modules, one-page opening, preserved quantity, subject direct identity and historical shop guards rendered successfully.');

assert.ok(!media.includes('确认指派'),'媒介不应看到主管派单');
assert.ok(media.includes('完成本次开户'),'媒介必须看到明确结束入口');
assert.ok(media.indexOf('开户账户明细')<media.indexOf('客户与主体资料'),'办理应先于历史资料');
const supervisor=renderToString(<CoreModule {...p} db={fixture} session={{role:'媒介主管',name:'主管'}} moduleId="M06" params={{applicationId:'app-ui-test'}}/>);
assert.ok(supervisor.includes('确认指派'));assert.ok(!supervisor.includes('填写开户结果'));
const otherMedia=renderToString(<CoreModule {...p} db={fixture} session={{role:'开户媒介',name:'另一媒介'}} moduleId="M06" params={{applicationId:'app-ui-test'}}/>);
assert.ok(!otherMedia.includes('填写开户结果'));assert.ok(!otherMedia.includes('完成本次开户'));
const work=renderToString(<CoreModule {...p} db={fixture} session={{role:'开户媒介',name:'媒介'}} moduleId="M01"/>);
assert.ok(work.includes('资料待补'));assert.ok(work.includes('已完成'));assert.ok(work.includes('申请单号：'));assert.ok(!work.includes('全部演示待办'));assert.ok(!work.includes('确认到账'));

for(const label of ['编辑主体资料','编辑店铺资料','添加备注','补充纵横 ID'])assert.ok(!otherMedia.includes(label),'他人媒介不可出现：'+label);
const mediaList=renderToString(<CoreModule {...p} db={fixture} session={{role:'开户媒介',name:'媒介'}} moduleId="M06" params={{}}/>);
assert.ok(!mediaList.includes('新增开户'));
const blockedNew=renderToString(<CoreModule {...p} db={fixture} session={{role:'开户媒介',name:'媒介'}} moduleId="M06" params={{mode:'new'}}/>);
assert.ok(blockedNew.includes('请由商务提交开户申请'));assert.ok(!blockedNew.includes('提交开户申请</button>'));
fixture.applications.at(-1).events.push({at:new Date().toISOString(),type:'flow-note',text:'流转备注：安排演示（演示）培训'});
const literalNote=renderToString(<CoreModule {...p} db={fixture} session={{role:'开户媒介',name:'媒介'}} moduleId="M06" params={{applicationId:'app-ui-test'}}/>);
assert.ok(literalNote.includes('流转备注：安排演示（演示）培训'),'用户备注不能被显示文案清理改写');

// 批量办理只给当前办理人；成功行锁定，待办理行仍在原申请编辑。
for(const label of ['开户账户批量录入表','批量供应商','保存全部草稿','登记选中账户成功（2）','第2行广告账户ID','异常处理'])assert.ok(media.replace(/<!--.*?-->/g,'').includes(label),label);
assert.ok(!media.includes('第1行广告账户ID'),'成功行不再出现可编辑ID');
for(const html of [supervisor,otherMedia])for(const label of ['批量供应商','保存全部草稿','登记选中账户成功','第2行广告账户ID'])assert.ok(!html.includes(label),'非办理身份不出现 '+label);
fixture.subjects.find(s=>s.id==='subject-ui-test').customerIds.push('customer-empty-ui');
const sharedNoCustomer=renderToString(<CoreModule {...p} db={fixture} moduleId="M03" params={{subjectId:'subject-ui-test',shopId:'shop-ui-test'}}/>);
assert.ok(sharedNoCustomer.includes('本主体关联多个客户，请先选择本次客户'));
assert.match(sharedNoCustomer,/disabled="">在此开户/);
const sharedWithCustomer=renderToString(<CoreModule {...p} db={fixture} moduleId="M03" params={{customerId,subjectId:'subject-ui-test',shopId:'shop-ui-test'}}/>);
assert.ok(!/disabled="">在此开户/.test(sharedWithCustomer));
const filteredList=renderToString(<CoreModule {...p} db={fixture} moduleId="M06" params={{}} viewState={{openingListQuery:'已保存的检索词',openingListFilter:'办理中'}}/>);
assert.ok(filteredList.includes('value="已保存的检索词"'));
assert.ok(filteredList.includes('<option selected="">办理中</option>'));
