import React,{useState,useEffect} from 'react';
import {Badge,Notice,PageHeader,Section,Field,Modal,DataTable} from './ui.jsx';
import {SubjectEditor,ShopEditor,SupplierEditor} from './CoreFields.jsx';
import OpeningAttachments from './OpeningAttachments.jsx';
import OpeningBatchTable from './OpeningBatchTable.jsx';
import {isOpeningBatchEditable,openingRowDraft,saveOpeningBatchDraft,registerOpeningBatchSuccess,recordOpeningRowResult} from './opening-batch.js';
import {getSubjectDirect,canMaintainPublic,subjectValues,SUBJECT_FIELDS} from './core-fields.js';
import {openingWorkbenchRecords} from './opening-workbench.js';
import {allowed,supplierEligible,assignOpening,approveOpeningStep,cancelOpeningRow,canHandleOpening,completeOpeningApplication,saveAccountZongheng} from './model.js';

export const personLabel=value=>value==='演示开户媒介'?'开户媒介一':String(value||'').replace(/^演示/,'');
const nameOf=(rows,id)=>rows.find(r=>r.id===id)?.name||'未登记';
export function openingProgress(db,app){
 const rows=app.rows||[],success=rows.filter(r=>r.status==='成功').length,cancelled=rows.filter(r=>r.status==='已取消').length;
 return {total:app.requestedCount??rows.length,success,cancelled,remaining:rows.length-success-cancelled,failed:rows.filter(r=>r.status==='失败').length,unknown:rows.filter(r=>r.status==='未知').length,sync:rows.filter(r=>r.status==='待同步').length,supplement:app.product==='本地推'?rows.filter(r=>r.status==='成功'&&!(db.accounts.find(a=>a.id===r.accountId)?.zonghengId||r.zonghengId)).length:0};
}
export function ZonghengEditor({db,accountId,session,update,toast,onClose}){
 const account=db.accounts.find(a=>a.id===accountId),[value,setValue]=useState(account?.zonghengId||''),[note,setNote]=useState(''),[error,setError]=useState('');
 if(!account)return null;
 return <Modal title="补充纵横 ID" onClose={onClose} footer={<><button className="btn" data-modal-close>取消</button><button className="btn primary" onClick={()=>{try{update(d=>saveAccountZongheng(d,accountId,value,{session,note}),'补充纵横 ID');toast('纵横 ID 已保存');onClose()}catch(e){setError(e.message)}}}>保存纵横 ID</button></>}>
  <dl className="kv"><dt>客户名称</dt><dd>{nameOf(db.customers,account.customerId)}</dd><dt>账户名称</dt><dd>{account.name||'未填写'}</dd><dt>广告账户 ID</dt><dd className="mono">{account.externalId}</dd></dl>
  {error&&<Notice tone="error">{error}</Notice>}<Field label="纵横 ID" required><input value={value} onChange={e=>setValue(e.target.value)} placeholder="填写与本账户对应的纵横 ID"/></Field><Field label="流转备注（选填）"><textarea value={note} onChange={e=>setNote(e.target.value)}/></Field>
 </Modal>;
}
export default function OpeningApplication(p){
 const {db,app,session,update,toast,go,openAccount}=p;
 const [resultId,setResultId]=useState(null),[values,setValues]=useState({}),[error,setError]=useState(''),[publicEditor,setPublicEditor]=useState(null),[supplierId,setSupplierId]=useState(null),[zhAccount,setZhAccount]=useState(null),[busy,setBusy]=useState(false),[assignee,setAssignee]=useState(app.assignee||'演示开户媒介'),[confirmFinish,setConfirmFinish]=useState(false),[note,setNote]=useState(''),[finishNote,setFinishNote]=useState('');
 const progress=openingProgress(db,app),finished=['全部完成','已取消'].includes(app.status),confirmed=!!app.completionConfirmedAt||finished,canHandle=canHandleOpening(session,app),direct=getSubjectDirect(db,app.subjectId),shop=db.shops.find(s=>s.id===app.shopId),currentRow=app.rows.find(r=>r.id===resultId),syncOnly=currentRow?.status==='待同步';
 const [edits,setEdits]=useState({}),[selected,setSelected]=useState(()=>app.rows.filter(isOpeningBatchEditable).map(r=>r.id)),[batchErrors,setBatchErrors]=useState([]);
 const editableRows=app.rows.filter(isOpeningBatchEditable),canBatch=canHandle&&!confirmed;
 const rowValue=r=>edits[r.id]||openingRowDraft(r);
 const removeEdits=ids=>setEdits(previous=>Object.fromEntries(Object.entries(previous).filter(([id])=>!ids.includes(id))));
 const changeRows=patch=>setEdits(previous=>({...previous,...patch}));
 const saveAllDrafts=()=>{try{if(busy)throw Error('附件正在保存，请稍候。');const entries=editableRows.map(r=>({id:r.id,...rowValue(r)}));update(d=>{if(entries.length&&(canBatch||Object.keys(edits).length))saveOpeningBatchDraft(d,app.id,entries,session);if(note.trim()){const a=d.applications.find(x=>x.id===app.id);requireAppEdit(a);a.events.push({at:new Date().toISOString(),actor:session.name,type:'flow-note',text:'流转备注：'+note.trim()})}},'保存开户办理草稿');setEdits({});setNote('');setBatchErrors([]);toast('办理草稿已保存，可从本申请继续');return true}catch(e){setBatchErrors(e.rowErrors||[{field:'general',message:e.message}]);toast(e.message,'error');return false}};
 const registerBatch=()=>{try{if(busy)throw Error('附件正在保存，请稍候。');const entries=editableRows.filter(r=>selected.includes(r.id)).map(r=>({id:r.id,...rowValue(r)}));update(d=>registerOpeningBatchSuccess(d,app.id,entries,session),'批量登记开户成功');removeEdits(entries.map(r=>r.id));setSelected([]);setBatchErrors([]);toast('已登记 '+entries.length+' 个账户成功；全部处理后请完成本次开户')}catch(e){setBatchErrors(e.rowErrors||[{field:'general',message:e.message}]);toast('本次未登记，请核对表格中的提示','error')}};
 const canEditApplication=canMaintainPublic(session)&&(session.role!=='开户媒介'||canHandle);
 useEffect(()=>{p.onDirtyChange?.(busy||!!note.trim()||Object.keys(edits).length>0);return()=>p.onDirtyChange?.(false)},[busy,note,edits,p.onDirtyChange]);
 useEffect(()=>{p.registerDraftSaver?.(canEditApplication?saveAllDrafts:null);return()=>p.registerDraftSaver?.(null)},[busy,note,edits,app,canEditApplication,update,p.registerDraftSaver]);
 const requireAppEdit=a=>{if(!canMaintainPublic(session)||session.role==='开户媒介'&&!canHandleOpening(session,a))throw Error('只能维护指派给自己的开户申请资料。')};
 const canFinish=canHandle&&progress.remaining===0&&!confirmed&&app.rows.length>0&&Object.keys(edits).length===0;
 const pendingStep=openingWorkbenchRecords(db).find(r=>r.recordId===app.id)?.step;
 const begin=r=>{setResultId(r.id);setValues({...openingRowDraft(r),...edits[r.id],verificationReason:'',cancelReason:''});setError('')};
 const saveProgress=()=>{try{update(d=>saveOpeningBatchDraft(d,app.id,[{id:resultId,...values}],session),'保存开户办理进度');removeEdits([resultId]);setResultId(null);toast('办理进度已保存，可从待办继续这笔申请')}catch(e){setError(e.message)}};
 const record=outcome=>{try{if(busy)throw Error('附件正在保存，请稍候');update(d=>recordOpeningRowResult(d,app.id,resultId,outcome,values,session),'登记开户结果');removeEdits([resultId]);setResultId(null);toast('账户结果已保存；全部处理后请点击“完成本次开户”')}catch(e){setError(e.message)}};
 const noteEvent=()=>{try{if(!note.trim())return;update(d=>{const a=d.applications.find(x=>x.id===app.id);requireAppEdit(a);a.events.push({at:new Date().toISOString(),text:personLabel(session.name)+'：'+note.trim(),note:note.trim(),actor:session.name})},'添加开户流转备注');setNote('');toast('备注已添加')}catch(e){toast(e.message,'error')}};
 return <div className="opening-page">
  <PageHeader eyebrow="开户申请" title={nameOf(db.customers,app.customerId)+' · 开户办理'} description={'申请单号：'+app.id+' · '+app.product+' · '+app.region} actions={<><button className="btn" onClick={()=>go('M01')}>返回工作台</button><button className="btn" onClick={()=>go('M06')}>返回申请列表</button></>}/>
  <div className="opening-status-bar"><div><Badge tone={finished?'green':'blue'}>{app.status==='全部完成'?'开户已完成':app.status}</Badge><span>开户媒介：{personLabel(app.assignee)||'待指派'}</span><span>负责商务：{personLabel(app.businessOwnerName)||'未指定'}</span></div>{canHandle&&!confirmed&&<button className="btn primary" disabled={!canFinish||busy} onClick={()=>{setError('');setConfirmFinish(true)}}>完成本次开户</button>}</div>
  <div className="opening-progress" aria-label="开户数量进度">{[['申请数量',progress.total],['开户成功',progress.success],['待处理',progress.remaining],['已取消',progress.cancelled]].map(([label,count])=><div key={label}><span>{label}</span><strong>{count}</strong></div>)}<small>{confirmed?(progress.supplement?'开户结果已确认，另有 '+progress.supplement+' 个账户可补充纵横 ID。':'开户结果已确认。'):progress.remaining?'按下方账户明细办理；保存后可随时退出并继续。':'账户已全部处理，请点击“完成本次开户”。'}</small></div>
  {!!(progress.failed||progress.unknown||progress.sync)&&<Notice tone="amber">{progress.failed?progress.failed+' 个开户失败，需重试或取消。 ':''}{progress.unknown?progress.unknown+' 个结果待核实。 ':''}{progress.sync?progress.sync+' 个等待同步账户结果。':''}</Notice>}
  {!app.assignee&&!allowed(session,'assign')&&<Notice>申请已提交，等待主管指派开户媒介。</Notice>}
  {app.assignee&&session.role==='开户媒介'&&!canHandle&&<Notice>本单由 {personLabel(app.assignee)} 办理。你可以查看进度。</Notice>}
  {allowed(session,'assign')&&!confirmed&&<Section title={app.assignee?'调整开户媒介':'指派开户媒介'}><div className="opening-assignment"><Field label="开户媒介"><select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="演示开户媒介">开户媒介一</option><option value="演示开户媒介二">开户媒介二</option></select></Field><button className="btn primary" disabled={!progress.remaining} onClick={()=>{try{update(d=>assignOpening(d,app.id,assignee,session.role),'指派开户媒介');toast('已指派开户媒介')}catch(e){toast(e.message,'error')}}}>确认指派</button></div></Section>}
  {pendingStep&&<Section title="流程审批"><p>当前步骤：{pendingStep.name} · {pendingStep.role}</p>{[pendingStep.role,'系统管理员'].includes(session.role)&&(session.role!=='开户媒介'||canHandle)&&<button className="btn primary" onClick={()=>{try{update(d=>approveOpeningStep(d,app.id,pendingStep.id,session.role,session),'完成审批步骤');toast('审批已完成')}catch(e){toast(e.message,'error')}}}>完成{pendingStep.name}</button>}</Section>}
  <Section title="开户账户明细" actions={<span className="muted">共 {progress.total} 个账户{progress.supplement?' · '+progress.supplement+' 个纵横 ID 待补':''}</span>}>
   <div className="batch-context"><span>主体：<strong>{nameOf(db.subjects,app.subjectId)}</strong></span><span>店铺：<strong>{shop?.name||'未登记'}</strong></span></div>
   <OpeningBatchTable db={db} app={app} canEdit={canBatch} busy={busy} edits={edits} onEdit={changeRows} selected={selected} onSelect={setSelected} errors={batchErrors} onDraft={saveAllDrafts} onRegister={registerBatch} onException={begin} onSupplier={setSupplierId} onAccount={openAccount} onZongheng={setZhAccount} canEditZongheng={allowed(session,'edit')&&(!app.assignee||canHandle||session.role==='媒介主管')} toast={toast}/>
  </Section>
  <Section title="客户与主体资料" actions={<>{canEditApplication&&<><button className="btn" disabled={busy} onClick={()=>setPublicEditor('subject')}>编辑主体资料</button><button className="btn" disabled={busy} onClick={()=>setPublicEditor('shop')}>编辑店铺资料</button></>}</>}><div className="grid2"><dl className="kv"><dt>客户名称</dt><dd>{nameOf(db.customers,app.customerId)}</dd><dt>主体名称（直客名称）</dt><dd>{nameOf(db.subjects,app.subjectId)}</dd><dt>直客 ID</dt><dd>{direct.directId||'未填写'}</dd></dl><dl className="kv"><dt>店铺名称（来客名称）</dt><dd>{shop?.name||'未登记'}</dd><dt>来客 ID</dt><dd>{shop?.laikeId||'未填写'}</dd><dt>申请人</dt><dd>{personLabel(app.submittedBy)||'未记录'}</dd></dl></div><details className="opening-history"><summary>查看提交时的资料</summary><dl className="kv">{app.subjectSnapshot?Object.entries(subjectValues(app.subjectSnapshot)).filter(([,v])=>v).map(([key,value])=><React.Fragment key={key}><dt>{SUBJECT_FIELDS.find(f=>f[0]===key)?.[1]||key}</dt><dd>{value}</dd></React.Fragment>):<p>未保存提交时资料</p>}<dt>提交时来客 ID</dt><dd>{app.shopSnapshot?.laikeId||'未填写'}</dd></dl></details></Section>
  <details className="section opening-materials"><summary>营业执照与资质（{app.attachments?.length||0} 份）</summary><OpeningAttachments onBusyChange={setBusy} files={app.attachments||[]} product={app.product} workflow={{fields:app.fieldSnapshot||[],attachmentPolicies:app.attachmentPolicySnapshot}} subjectId={app.subjectId} readOnly={confirmed||!canEditApplication} onChange={files=>update(d=>{const a=d.applications.find(a=>a.id===app.id);requireAppEdit(a);if(a.completionConfirmedAt||['全部完成','已取消'].includes(a.status))throw Error('已完成申请不可修改附件。');a.attachments=files;a.events.push({at:new Date().toISOString(),text:personLabel(session.name)+'更新开户附件'})},'更新开户附件')}/></details>
  <Section title="申请备注"><p>{app.note||'未填写'}</p>{Object.entries(app.customValues||{}).filter(([,v])=>String(v).trim()).map(([key,value])=><p key={key}>{app.fieldSnapshot?.find(f=>f.id===key)?.label||key}：{String(value)}</p>)}</Section>
  <Section title="流转记录">{canEditApplication&&<div className="opening-note"><Field label="流转备注（选填）"><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="填写需要交接或补充说明的事项"/></Field><button className="btn" disabled={!note.trim()} onClick={noteEvent}>添加备注</button></div>}<div className="timeline">{app.events.map((e,i)=><div key={i}><small>{new Date(e.at).toLocaleString('zh-CN')}</small><p>{e.text}</p></div>)}</div></Section>
  {canHandle&&!confirmed&&<div className="opening-completion"><div><strong>{progress.remaining?'还有 '+progress.remaining+' 个账户待处理':'全部账户已处理'}</strong><span>已保存的进度会保留在本申请中</span></div><button className="btn" onClick={()=>go('M01')}>返回工作台</button><button className="btn primary" disabled={!canFinish||busy} onClick={()=>{setError('');setConfirmFinish(true)}}>完成本次开户</button></div>}
  {resultId&&<Modal title={'第 '+(app.rows.indexOf(currentRow)+1)+' 个账户 · '+(syncOnly?'同步开户结果':currentRow.status==='未知'?'核实开户结果':'异常处理')} onClose={()=>setResultId(null)} footer={<><button className="btn" data-modal-close>返回申请</button>{['待办理','失败'].includes(currentRow.status)&&<button className="btn" onClick={saveProgress}>保存办理进度</button>}<button className="btn primary" onClick={()=>record('成功')}>{syncOnly?'确认同步完成':'保存开户成功结果'}</button></>}>
   {error&&<Notice tone="error">{error}</Notice>}<p>开户供应商：{nameOf(db.suppliers,values.supplierId||currentRow.supplierId)}</p><Field label="广告账户名称（选填）"><input disabled={syncOnly} value={values.name||''} onChange={e=>setValues({...values,name:e.target.value})}/></Field><Field label="广告账户 ID" required><input disabled={syncOnly} value={values.externalId||''} onChange={e=>setValues({...values,externalId:e.target.value})} placeholder="填写平台返回的完整账户 ID"/></Field>{app.product==='本地推'&&<Field label="纵横 ID（选填，可后补）"><input value={values.zonghengId||''} onChange={e=>setValues({...values,zonghengId:e.target.value})}/></Field>}
   {!syncOnly&&<details className="opening-exceptions"><summary>开户失败、结果待核实或取消</summary>{currentRow.status==='未知'?<><Field label="核实说明" required><textarea value={values.verificationReason||''} onChange={e=>setValues({...values,verificationReason:e.target.value})}/></Field><button className="btn" onClick={()=>record('核实未发生')}>确认未开户</button></>:<><button className="btn" onClick={()=>record('失败')}>登记开户失败</button><button className="btn" onClick={()=>record('未知')}>结果待核实</button><Field label="取消原因"><input value={values.cancelReason||''} onChange={e=>setValues({...values,cancelReason:e.target.value})}/></Field><button className="btn danger" onClick={()=>{try{update(d=>cancelOpeningRow(d,app.id,currentRow.id,values.cancelReason,session),'取消本次账户开户');removeEdits([resultId]);setResultId(null)}catch(e){setError(e.message)}}}>取消此账户开户</button></>}<button className="btn" onClick={()=>record('待同步')}>开户成功，稍后同步</button></details>}
  </Modal>}
  {confirmFinish&&<Modal title="完成本次开户" onClose={()=>setConfirmFinish(false)} footer={<><button className="btn" data-modal-close>继续核对</button><button className="btn primary" onClick={()=>{try{update(d=>completeOpeningApplication(d,app.id,session,{note:finishNote}),'完成本次开户');setConfirmFinish(false);toast((app.flowSnapshot||[]).some(s=>!['s1','s2','s3','s4'].includes(s.id)&&!app.configApprovals?.[s.id])?'开户结果已确认，等待后续审批':'本次开户已完成，可在工作台“已完成”中查看')}catch(e){setError(e.message)}}}>确认完成</button></>}><p>本次申请 {progress.total} 个账户，开户成功 {progress.success} 个，已取消 {progress.cancelled} 个。</p>{!!progress.supplement&&<p>其中 {progress.supplement} 个账户尚未填写纵横 ID，可在开户完成后继续补充。</p>}<Field label="流转备注（选填）"><textarea value={finishNote} onChange={e=>setFinishNote(e.target.value)}/></Field>{error&&<Notice tone="error">{error}</Notice>}</Modal>}
  {publicEditor==='subject'&&<SubjectEditor {...p} applicationId={app.id} subjectId={app.subjectId} customerId={app.customerId} onSaved={()=>toast('主体资料已保存')} onClose={()=>setPublicEditor(null)}/>}
  {publicEditor==='shop'&&<ShopEditor {...p} applicationId={app.id} subjectId={app.subjectId} shopId={app.shopId} product={app.product} onSaved={()=>toast('店铺资料已保存')} onClose={()=>setPublicEditor(null)}/>}
  {supplierId&&<SupplierEditor {...p} supplierId={supplierId} readOnly onClose={()=>setSupplierId(null)}/>}
  {zhAccount&&<ZonghengEditor {...p} accountId={zhAccount} onClose={()=>setZhAccount(null)}/>}
 </div>;
}
