import React,{useState,useEffect,useCallback,useRef} from 'react';
import seed from './realData.json';
import modules from './moduleDefs.json';
import {STORE_KEY,ROLES,freshState,uid} from './model.js';
import CoreModule,{AccountDetail} from './CoreModule.jsx';
import FinanceModule from './FinanceModule.jsx';
import OperationsModule from './OperationsModule.jsx';
import {getVisibleNotifications} from './opening-notifications.js';
import {Modal,Notice,ViewScopeContext,ModalDirtyContext,createModalDirtyRegistry} from './ui.jsx';
import {NAV_GROUPS,normalizeRoute,parseRoute,routeKey,routeHash,routePhase,createRouteHistory,nextRouteTrail} from './navigation.js';
const groups=NAV_GROUPS;
const titles={M01:'个人工作台',M02:'客户与全局检索',M03:'主体与店铺档案',M04:'供应商与能力',M05:'广告账户总表',M06:'开户申请与办理',M07:'复制资料开户',M08:'归属交接与协办',M09:'到账与认领',M10:'客户 / 渠道总账',M11:'授信与欠款',M12:'广告账户充值',M13:'续费业务',M14:'平台退币',M15:'客户现金退款',M16:'渠道 CRM 转账',M17:'平台余额转户',M18:'供应商往来',M19:'返点与服务费',M20:'合同档案',M21:'开票办理',M22:'对账与差异',M23:'报销与采购',M24:'消耗与匹配',M25:'经营报表',M26:'收益与提成',M27:'激励政策',M28:'素材与绩效',M29:'员工与任职',M30:'考勤与休假',M31:'薪资管理',M32:'考核与目标',M33:'角色与权限',M34:'表单与工作流',M35:'站内信与企微',M36:'导入导出与附件',M37:'迁移与历史核对',M38:'公海与跟进',M39:'审计与业务期间',M40:'同步与任务'};
function readRoute(){return parseRoute(location.hash)}
class ErrorBoundary extends React.Component{constructor(p){super(p);this.state={error:null}}static getDerivedStateFromError(error){return{error}}componentDidCatch(error){console.error('Prototype UI error',error)}render(){if(this.state.error)return <div className="page"><h1>页面未能完成加载</h1><p>{String(this.state.error.message)}</p><button className="btn" onClick={()=>{this.setState({error:null});this.props.recover()}}>返回工作台</button></div>;return this.props.children}}
export function App(){
  const [db,setDb]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem(STORE_KEY));return saved?.provenanceVersion===2?saved:freshState(seed)}catch{return freshState(seed)}});
  const [route,setRoute]=useState(readRoute),[role,setRole]=useState(()=>{try{return sessionStorage.getItem('xinhuo-role')||'商务主管'}catch{return '商务主管'}}),[mediaName,setMediaName]=useState(()=>{try{return sessionStorage.getItem('xinhuo-media')||'演示开户媒介'}catch{return '演示开户媒介'}}),[businessId,setBusinessId]=useState(()=>{try{return sessionStorage.getItem('xinhuo-business')||'demo-sales-a'}catch{return 'demo-sales-a'}}),[pendingIdentity,setPendingIdentity]=useState(null),[identityEpoch,setIdentityEpoch]=useState(0),[query,setQuery]=useState(''),[accountId,setAccountId]=useState(null),[dialog,setDialog]=useState(null),[note,setNote]=useState(null),[navQuery,setNavQuery]=useState(''),[pendingNav,setPendingNav]=useState(null),[isDirty,setIsDirty]=useState(false),[trail,setTrail]=useState([]),[views,setViews]=useState(()=>{try{return JSON.parse(sessionStorage.getItem('xinhuo-module-views-v2')||'{}')}catch{return {}}});
  const session={role,businessId,name:role==='商务'||role==='渠道商务'?(businessId==='demo-sales-a'?'演示商务 A':'演示商务 B'):role==='开户媒介'?mediaName:'演示'+role};
  useEffect(()=>{try{sessionStorage.setItem('xinhuo-role',role);sessionStorage.setItem('xinhuo-media',mediaName);sessionStorage.setItem('xinhuo-business',businessId)}catch{}},[role,mediaName,businessId]);
  useEffect(()=>{if(route.id==='M05'&&route.params.accountId)setAccountId(route.params.accountId)},[route.id,route.params.accountId]);
  const toast=useCallback((message,tone='success')=>{setNote({message,tone,id:Date.now()});setTimeout(()=>setNote(null),4500)},[]);
  const routeRef=useRef(route),dirtyRef=useRef(false),pageDirtyRef=useRef(false),modalRegistry=useRef(null),saverRef=useRef(null),scrollRef=useRef(new Map()),identityRef=useRef(role+':'+session.name),historyController=useRef(null);identityRef.current=role+':'+session.name;
  const refreshDirty=useCallback(()=>{const value=pageDirtyRef.current||!!modalRegistry.current?.hasDirty();dirtyRef.current=value;setIsDirty(value)},[]);
  if(!modalRegistry.current)modalRegistry.current=createModalDirtyRegistry(refreshDirty);
  const onDirtyChange=useCallback(value=>{pageDirtyRef.current=!!value;refreshDirty()},[refreshDirty]);
  const registerDraftSaver=useCallback(fn=>{saverRef.current=fn},[]);
  const performNavigation=useCallback((next,options={})=>{
    const previous=options.previous||routeRef.current;if(routeKey(previous)===routeKey(next))return;
    scrollRef.current.set(routeKey(previous),window.scrollY);
    setTrail(old=>nextRouteTrail(old,previous,next,options));
    pageDirtyRef.current=false;modalRegistry.current.clear();dirtyRef.current=false;setIsDirty(false);saverRef.current=null;setAccountId(null);setDialog(null);routeRef.current=next;setRoute(next);setPendingNav(null);
    requestAnimationFrame(()=>window.scrollTo(0,scrollRef.current.get(routeKey(next))||0));
  },[]);
  const go=useCallback((id,params={},options={})=>historyController.current?.navigate(normalizeRoute(id,params),options),[]);
  useEffect(()=>{
    const controller=createRouteHistory({history,readRoute,isDirty:()=>dirtyRef.current,onApply:performNavigation,onBlocked:setPendingNav});historyController.current=controller;
    const fn=()=>controller.onPop();window.addEventListener('popstate',fn);window.addEventListener('hashchange',fn);
    const unload=e=>{if(dirtyRef.current){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',unload);
    return()=>{window.removeEventListener('popstate',fn);window.removeEventListener('hashchange',fn);window.removeEventListener('beforeunload',unload);historyController.current=null};
  },[performNavigation]);
  const setViewState=useCallback(patch=>{const key=identityRef.current+':'+routeRef.current.id;setViews(old=>{const next={...old,[key]:{...(old[key]||{}),...patch}};if(JSON.stringify(next)===JSON.stringify(old))return old;try{sessionStorage.setItem('xinhuo-module-views-v2',JSON.stringify(next))}catch{}return next})},[]);
  const confirmLeave=save=>{try{if(save&&saverRef.current){const ok=saverRef.current();if(ok===false)return;}pageDirtyRef.current=false;modalRegistry.current.clear();dirtyRef.current=false;setIsDirty(false);setPendingNav(null);historyController.current?.navigate(pendingNav.next,{...pendingNav.options,committed:true})}catch(e){toast(e.message||'保存未成功，当前输入仍保留。','error')}};
  const applyIdentity=change=>{pageDirtyRef.current=false;modalRegistry.current.clear();dirtyRef.current=false;setIsDirty(false);saverRef.current=null;setAccountId(null);setDialog(null);setPendingNav(null);setPendingIdentity(null);if(change.kind==='role')setRole(change.value);else if(change.kind==='media')setMediaName(change.value);else setBusinessId(change.value);setIdentityEpoch(n=>n+1);};
  const requestIdentity=(kind,value)=>{const change={kind,value};if(dirtyRef.current)setPendingIdentity(change);else applyIdentity(change)};
  const confirmIdentity=save=>{try{if(save&&saverRef.current&&saverRef.current()===false)return;applyIdentity(pendingIdentity)}catch(e){toast(e.message||'保存未成功，当前输入仍保留。','error')}};
  const commitDb=useCallback(next=>{try{localStorage.setItem(STORE_KEY,JSON.stringify(next))}catch{const error=new Error('保存失败，浏览器存储不可用或空间不足。当前输入仍保留，请勿关闭页面。');toast(error.message,'error');throw error;}setDb(next)},[toast]);
  useEffect(()=>{const receive=e=>{if(e.key!==STORE_KEY||!e.newValue)return;try{const current=JSON.parse(e.newValue);if(current.provenanceVersion===2)setDb(current)}catch{}};window.addEventListener('storage',receive);return()=>window.removeEventListener('storage',receive)},[]);
  const update=useCallback((fn,action='本地原型操作')=>{let current=db;try{const saved=JSON.parse(localStorage.getItem(STORE_KEY));if(saved?.provenanceVersion===2)current=saved}catch{}const next=structuredClone(current);fn(next);next.audit.unshift({id:uid('LOG'),at:new Date().toISOString(),actor:session.name,action});commitDb(next)},[db,session.name,commitDb]);
  const module=modules.find(m=>m.id===route.id),currentGroup=groups.find(g=>g.ids.includes(route.id)),phase=routePhase(route),viewState=views[role+':'+session.name+':'+route.id]||{},props={moduleId:route.id,params:route.params,db,session,update,go,toast,openAccount:setAccountId,onDirtyChange,registerDraftSaver,viewState,setViewState};
  return <ModalDirtyContext.Provider value={modalRegistry.current}><div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-word">薪火</span><div>CRM<span>业务协作工作空间</span></div></div><div className="workspace-label">业务导航</div><div className="nav-search"><input aria-label="查找功能菜单" value={navQuery} onChange={e=>setNavQuery(e.target.value)} placeholder="查找功能，如开户、退款"/>{navQuery&&<button onClick={()=>setNavQuery('')}>清除</button>}</div><div className="current-location"><small>当前位置</small><strong>{titles[route.id]}</strong>{phase&&<span>{phase}</span>}</div><nav aria-label="业务功能导航">{groups.map(g=>{const ids=g.ids.filter(id=>!navQuery||titles[id].includes(navQuery)||g.name.includes(navQuery));return ids.length?<section className="nav-group" key={g.name} aria-label={g.name}><h2 className="nav-section-heading">{g.name}</h2><div className="nav-children">{ids.map(id=><button key={id} className={'nav-item '+(route.id===id?'active':'')} aria-current={route.id===id?'page':undefined} onClick={()=>go(id)}><span>{titles[id]}</span>{route.id===id&&<small>当前</small>}</button>)}</div></section>:null})}{navQuery&&!groups.some(g=>g.ids.some(id=>titles[id].includes(navQuery)||g.name.includes(navQuery)))&&<p className="nav-empty">没有找到此功能，可修改关键词。</p>}</nav><div className="sidebar-footer"><button onClick={()=>setDialog('coverage')}>功能目录与说明</button><span>薪火 CRM</span></div></aside>
  <div className="main-shell"><header className="topbar"><div className="breadcrumb"><small>{currentGroup.name}</small><strong>{titles[route.id]}{phase&&<span> / {phase}</span>}</strong></div><form className="global-search" onSubmit={e=>{e.preventDefault();go('M02',{query})}}><input aria-label="全局搜索" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜客户、主体、店铺、账户 ID"/><button type="submit">搜索</button></form><button className="btn quiet notification-btn" onClick={()=>go('M35')}>消息 <b>{getVisibleNotifications(db,session).filter(n=>!n.read).length}</b></button><select aria-label="切换角色" className="role-switch" value={role} onChange={e=>requestIdentity('role',e.target.value)}>{ROLES.map(r=><option key={r}>{r}</option>)}</select>{role==='开户媒介'&&<select aria-label="切换开户媒介身份" value={mediaName} onChange={e=>requestIdentity('media',e.target.value)}><option value="演示开户媒介">开户媒介一</option><option value="演示开户媒介二">开户媒介二</option></select>}{['商务','渠道商务'].includes(role)&&<select aria-label="切换商务身份" value={businessId} onChange={e=>requestIdentity('business',e.target.value)}><option value="demo-sales-a">商务 A</option><option value="demo-sales-b">商务 B</option></select>}</header>
  <div className="prototype-strip"><span><b>演示环境</b> · 操作仅保存在本机，不影响正式业务</span><div><button onClick={()=>setDialog('source')}>数据来源</button><button onClick={()=>setDialog('reset')}>恢复演示数据</button></div></div>
  <div className="journey-bar">{trail.length>0?<button className="btn quiet" onClick={()=>{const previous=trail[trail.length-1];go(previous.id,previous.params,{back:true})}}>返回来源：{titles[trail[trail.length-1].id]}</button>:<span>当前功能：{titles[route.id]}</span>}<span className={isDirty?'draft-indicator dirty':'draft-indicator'}>{isDirty?'有未保存的输入':phase||'可从列表继续办理原单'}</span></div>
  <ViewScopeContext.Provider value={role+':'+session.name+':'+route.id}><main className="page"><ErrorBoundary key={role+':'+session.name+':'+identityEpoch+':'+route.id} recover={()=>go('M01')}>{Number(route.id.slice(1))<=8?<CoreModule {...props}/>:Number(route.id.slice(1))<=22?<FinanceModule {...props}/>:<OperationsModule {...props}/>}</ErrorBoundary></main></ViewScopeContext.Provider>
  <footer className="app-footer"><span>{route.id} · {module.title}</span><button onClick={()=>setDialog('rules')}>查看本页业务规则</button><span>本地演示环境</span></footer></div>
  {note&&<div className={'toast '+note.tone} role="status">{note.message}</div>}
  {accountId&&<AccountDetail accountId={accountId} db={db} session={session} update={update} go={go} toast={toast} onClose={()=>setAccountId(null)}/>}
  {dialog==='source'&&<Modal title="数据来源与真实范围" onClose={()=>setDialog(null)} wide><Notice>本地数据来自已保存的只读查询结果及数据库备份。并非本轮实时生产查询，也不是生产全量数据。</Notice><div className="metrics compact">{[['客户',seed.customers.length],['主体',seed.subjects.length],['店铺 / 档案',seed.shops.length],['广告账户',seed.accounts.length]].map(([l,n])=><div className="metric" key={l}><span>{l}</span><strong>{n}</strong></div>)}</div><p>{db.meta.note}</p><p>{typeof db.meta.sampleScope==='string'?db.meta.sampleScope:JSON.stringify(db.meta.sampleScope)}</p><h3>不能从样本推断的内容</h3><ul><li>账户商务、直客、纵横没有可靠来源，保留未核验或未登记。</li><li>普通 WZ/DY/OM 旧编号不作为来客，只有互证店铺显示已核验值。</li><li>历史样本无银行、电话、真实资金余额；资金及人事场景均另标演示。</li><li>供应商产品清单是样本观察范围，不等于真实平台操作授权。</li></ul><details><summary>查看 7 份来源的路径与校验记录</summary><pre className="source">{JSON.stringify(db.meta.sources,null,2)}</pre></details></Modal>}
  {dialog==='rules'&&<Modal title={route.id+' · 业务与页面约束'} onClose={()=>setDialog(null)} wide><Notice>来自本轮 PRD V1.4：主体与直客一对一、商务按数量申请、媒介批量登记开户结果；外部接口仍为演示边界。</Notice><ul>{module.rules.map((r,i)=><li key={i}>{r}</li>)}</ul>{route.id==='M17'&&<Notice tone="amber">本轮补充：平台转户两端还需同归属商务。未知归属不能因两个空值而通过。</Notice>}{route.id==='M06'&&<Notice>本轮调整：商务在一页搜索和补全资料，用数量提交开户需求；媒介在原申请表内批量填写供应商与账户 ID，账户名称和纵横 ID 可空；保存草稿、登记成功与完成整单分开操作。</Notice>}<h3>字段契约</h3><div className="table-wrap"><table><thead><tr><th>字段</th><th>阶段</th><th>约束</th></tr></thead><tbody>{module.fields.map((f,i)=><tr key={i}><td>{f.label}</td><td>{f.required}</td><td>{f.constraint}</td></tr>)}</tbody></table></div></Modal>}
  {dialog==='reset'&&<Modal title="恢复原型演示数据" onClose={()=>setDialog(null)} footer={<button className="btn danger" onClick={()=>{commitDb(freshState(seed));setDialog(null);go('M01');toast('已恢复历史样本及初始演示状态。')}}>确认恢复本地原型</button>}><p>将清除当前浏览器中创建的演示申请、模拟资金、权限配置与操作记录，恢复原始样本。</p><p>此操作只影响本原型的浏览器本地状态。</p></Modal>}
  {dialog==='coverage'&&<Modal title="40 模块交互目录与评审范围" onClose={()=>setDialog(null)} wide><Notice>核心数据结构已按审查建议细化。所有模块均可进入与演示办理；外部开户、企微、银行付款和后端权限引擎尚未接入。</Notice><div className="coverage-grid">{groups.map(g=><section key={g.name}><h3>{g.name}</h3>{g.ids.map(id=><button key={id} onClick={()=>{setDialog(null);go(id)}}>{id} {titles[id]}</button>)}</section>)}</div><p>本轮 PRD V1.4 已按用户确认更新主体、店铺、直客关系与数量开户流程；本地界面演示与生产接口验收分别记录。</p></Modal>}
  {pendingIdentity&&<Modal title="切换身份前保存当前内容？" guardChanges={false} onClose={()=>setPendingIdentity(null)} footer={<><button className="btn" onClick={()=>setPendingIdentity(null)}>继续填写</button>{saverRef.current&&!modalRegistry.current.hasDirty()&&<button className="btn primary" onClick={()=>confirmIdentity(true)}>保存草稿并切换</button>}<button className="btn danger" onClick={()=>confirmIdentity(false)}>放弃未保存输入并切换</button></>}><p>当前页面有未保存的输入。切换身份后，将按所选人员的权限重新打开本页。</p>{modalRegistry.current.hasDirty()&&<Notice>弹窗中还有未保存资料，请返回并保存弹窗内容后再切换。</Notice>}</Modal>}
  {pendingNav&&<Modal title="离开当前办理页面？" guardChanges={false} onClose={()=>setPendingNav(null)} footer={<><button className="btn" onClick={()=>setPendingNav(null)}>继续填写</button>{saverRef.current&&!modalRegistry.current.hasDirty()&&<button className="btn primary" onClick={()=>confirmLeave(true)}>保存草稿并离开</button>}<button className="btn danger" onClick={()=>confirmLeave(false)}>放弃未保存输入并离开</button></>}><p>将从“{titles[route.id]}”前往“{titles[pendingNav.next.id]}”。当前尚有未保存的输入，业务单及已经保存的公共资料不会被删除。</p>{modalRegistry.current.hasDirty()&&<Notice>弹窗中另有尚未保存的资料。继续填写后请先保存该弹窗；开户草稿不包含尚未提交的弹窗输入。</Notice>}</Modal>}
  </div></ModalDirtyContext.Provider>
}
