import test from 'node:test';
import assert from 'node:assert/strict';
import {NAV_GROUPS,normalizeRoute,parseRoute,routeHash,routeKey,routePhase,createRouteHistory,nextRouteTrail} from '../src/navigation.js';
import {visibleColumns,orderedRows} from '../src/table-view.js';
test('40 个业务模块唯一且稳定分组，阶段不改变当前模块',()=>{const ids=NAV_GROUPS.flatMap(g=>g.ids);assert.equal(ids.length,40);assert.equal(new Set(ids).size,40);assert.equal(routePhase(normalizeRoute('M06',{mode:'new'})),'新增申请');assert.equal(parseRoute(routeHash({id:'M06',params:{applicationId:'KH-001'}})).id,'M06')});
test('同一目标参数顺序不同仍是同一路由，长编号保留字符串',()=>{const a={id:'M02',params:{accountId:'1873296142902524',customerId:'1115'}},b={id:'M02',params:{customerId:'1115',accountId:'1873296142902524'}};assert.equal(routeKey(a),routeKey(b));assert.deepEqual(parseRoute(routeHash(a)),normalizeRoute(a.id,a.params));assert.equal(parseRoute('#M06?broken').id,'M01')});
test('个人列设置保留身份与操作，新增字段不会被旧偏好吞掉',()=>{const columns=['name','owner','newField','actions'].map(key=>({key}));const result=visibleColumns(columns,{order:['owner','name','removed'],hidden:['name','owner','actions']});assert.deepEqual(result.map(c=>c.key),['name','newField','actions'])});
test('列表排序不修改源数组，不将长ID转换成不精确数字',()=>{const rows=[{id:'9999999999999999999'},{id:'9999999999999999998'}];assert.equal(orderedRows(rows,{key:'id',direction:'asc'})[0].id,'9999999999999999998');assert.equal(rows[0].id,'9999999999999999999')});
function historyFixture(){
 const entries=[{url:'#M01',state:null}],pending=[];let position=0,dirty=false,blocked=null,trail=[];
 const history={get state(){return entries[position].state},replaceState(state,_title,url){entries[position]={state,url}},pushState(state,_title,url){entries.splice(position+1);entries.push({state,url});position++},go(delta){pending.push(delta)}};
 const controller=createRouteHistory({history,readRoute:()=>parseRoute(entries[position].url),isDirty:()=>dirty,onBlocked:value=>blocked=value,onApply:(next,options)=>{trail=nextRouteTrail(trail,options.previous,next,options);dirty=false}});
 const flushOne=()=>{const delta=pending.shift();if(delta===undefined)return;const destination=position+delta;if(destination<0||destination>=entries.length)return;position=destination;controller.onPop()};
 return {entries,history,controller,flushOne,flush(){let max=20;while(pending.length&&max--)flushOne();assert.ok(max>0,'history did not settle')},setDirty(value){dirty=value},blocked:()=>blocked,position:()=>position,trail:()=>trail};
}
test('浏览器后退取消不会覆盖目的历史，之后仍可返回原目的地',()=>{const f=historyFixture();f.controller.navigate({id:'M02'});f.controller.navigate({id:'M06',params:{mode:'new'}});const original=f.entries.map(e=>e.url);f.setDirty(true);f.history.go(-1);f.flush();assert.equal(f.position(),2);assert.deepEqual(f.entries.map(e=>e.url),original);assert.equal(f.blocked().next.id,'M02');assert.equal(f.controller.current().id,'M06');f.setDirty(false);f.history.go(-1);f.flush();assert.equal(f.controller.current().id,'M02');assert.deepEqual(f.trail().map(r=>r.id),['M01'])});
test('确认保存后恢复精确的多步后退，保留前进历史',()=>{const f=historyFixture();f.controller.navigate({id:'M02'});f.controller.navigate({id:'M03'});f.controller.navigate({id:'M06'});f.setDirty(true);f.history.go(-2);f.flush();const blocked=f.blocked();f.setDirty(false);f.controller.navigate(blocked.next,{...blocked.options,committed:true});f.flush();assert.equal(f.controller.current().id,'M02');assert.equal(f.position(),1);assert.equal(f.entries.length,4);f.history.go(1);f.flush();assert.equal(f.controller.current().id,'M03')});
test('恢复浏览器位置尚未完成时确认离开，排队后只执行正确目的地',()=>{const f=historyFixture();f.controller.navigate({id:'M02'});f.controller.navigate({id:'M06'});f.setDirty(true);f.history.go(-1);f.flushOne();const blocked=f.blocked();f.setDirty(false);f.controller.navigate(blocked.next,{...blocked.options,committed:true});f.flush();assert.equal(f.position(),1);assert.equal(f.controller.current().id,'M02');assert.deepEqual(f.entries.map(e=>parseRoute(e.url).id),['M01','M02','M06'])});
test('内部导航未保存先阻拦，成功提交仅committed绕过并仍在M06',()=>{const f=historyFixture();f.controller.navigate({id:'M06',params:{mode:'new'}});f.setDirty(true);f.controller.navigate({id:'M05'});assert.equal(f.controller.current().id,'M06');assert.equal(f.blocked().next.id,'M05');f.controller.navigate({id:'M06',params:{applicationId:'KH-001'}},{committed:true});assert.equal(f.controller.current().params.applicationId,'KH-001');assert.equal(f.entries.length,3)});
test('popstate与hashchange重复通知不制造重复来源或历史记录',()=>{const f=historyFixture();f.controller.navigate({id:'M02'});f.controller.navigate({id:'M05'});f.history.go(-1);f.flush();const trail=f.trail();f.controller.onPop();assert.deepEqual(f.trail(),trail);assert.equal(f.entries.length,3);assert.equal(f.position(),1)});
