SELECT '## adv: type x customer_type x data_type x del_flag' AS _;
SELECT type, customer_type, data_type, del_flag, COUNT(*) n, SUM(run_status='0') running, MIN(create_time) first_created, MAX(create_time) last_created FROM dig_advertising_account GROUP BY type, customer_type, data_type, del_flag ORDER BY n DESC;
SELECT '## adv: type x supplier x dy_agentId (alive)' AS _;
SELECT a.type, a.supplier_id, s.supplier_name, s.suppliertype, s.pay_type, a.dy_agentId, COUNT(*) n FROM dig_advertising_account a LEFT JOIN dig_supplier s ON s.id=a.supplier_id WHERE a.del_flag='0' GROUP BY a.type, a.supplier_id, s.supplier_name, s.suppliertype, s.pay_type, a.dy_agentId ORDER BY n DESC;
SELECT '## adv created per month x type (18m)' AS _;
SELECT DATE_FORMAT(create_time,'%Y-%m') ym, type, COUNT(*) n FROM dig_advertising_account WHERE create_time >= DATE_SUB(CURDATE(), INTERVAL 18 MONTH) GROUP BY ym, type ORDER BY ym, type;
SELECT '## customer: types x customer_status x status x wallet x credit' AS _;
SELECT types, customer_status, status, del_flag, wallet_status, credit_datatype, credit_limit_type, COUNT(*) n FROM dig_customer GROUP BY types, customer_status, status, del_flag, wallet_status, credit_datatype, credit_limit_type ORDER BY n DESC;
SELECT '## customer created per month x types' AS _;
SELECT DATE_FORMAT(create_time,'%Y-%m') ym, types, COUNT(*) n FROM dig_customer GROUP BY ym, types ORDER BY ym, types;
SELECT '## subject: isapi x supplier x del_flag' AS _;
SELECT cs.isapi, cs.supplier_id, s.supplier_name, cs.del_flag, COUNT(*) n FROM dig_customer_subject cs LEFT JOIN dig_supplier s ON s.id=cs.supplier_id GROUP BY cs.isapi, cs.supplier_id, s.supplier_name, cs.del_flag ORDER BY n DESC;
SELECT '## subject.account_infojson keys' AS _;
SELECT JSON_KEYS(account_infojson) ks, COUNT(*) n FROM dig_customer_subject WHERE account_infojson IS NOT NULL AND account_infojson<>'' AND JSON_VALID(account_infojson) GROUP BY ks ORDER BY n DESC LIMIT 20;
SELECT '## subject.account_infojson empty/invalid' AS _;
SELECT SUM(account_infojson IS NULL OR account_infojson='') empty_n, SUM(account_infojson IS NOT NULL AND account_infojson<>'' AND NOT JSON_VALID(account_infojson)) invalid_n, COUNT(*) total FROM dig_customer_subject;
SELECT '## customer.account_infojson keys' AS _;
SELECT JSON_KEYS(account_infojson) ks, COUNT(*) n FROM dig_customer WHERE account_infojson IS NOT NULL AND account_infojson<>'' AND JSON_VALID(account_infojson) GROUP BY ks ORDER BY n DESC LIMIT 20;
SELECT '## shop.account_infojson keys' AS _;
SELECT JSON_KEYS(account_infojson) ks, COUNT(*) n FROM dig_shop WHERE account_infojson IS NOT NULL AND account_infojson<>'' AND JSON_VALID(account_infojson) GROUP BY ks ORDER BY n DESC LIMIT 20;
SELECT '## shop: supplier x del_flag' AS _;
SELECT supplier_id, del_flag, COUNT(*) n, SUM(subject_id>0) with_subject FROM dig_shop GROUP BY supplier_id, del_flag ORDER BY n DESC;
SELECT '## openapply: state x data_type x account_type x customer_type' AS _;
SELECT state, data_type, account_type, customer_type, COUNT(*) n, ROUND(AVG(TIMESTAMPDIFF(HOUR, create_time, reply_date)),1) avg_reply_h, MIN(create_time) first_t, MAX(create_time) last_t, ROUND(AVG(add_num),1) avg_addnum, SUM(supplier_name IS NOT NULL AND supplier_name<>'') has_supplier, SUM(account_nos IS NOT NULL AND account_nos<>'') has_accounts FROM dig_accountopen_apply GROUP BY state, data_type, account_type, customer_type ORDER BY n DESC;
SELECT '## openapply per month' AS _;
SELECT DATE_FORMAT(create_time,'%Y-%m') ym, COUNT(*) n, SUM(state='1') done FROM dig_accountopen_apply GROUP BY ym ORDER BY ym;
SELECT '## recharge: datatypes x approval_state x opentypes x sync x del x supplement' AS _;
SELECT datatypes, approval_state, opentypes, sync_state, del_flag, supplement_state, COUNT(*) n, ROUND(SUM(cash_recharge),0) cash_sum, ROUND(SUM(currency_recharge),0) currency_sum, ROUND(AVG(TIMESTAMPDIFF(HOUR, create_time, complete_time)),1) avg_h FROM dig_adveracoount_recharge GROUP BY datatypes, approval_state, opentypes, sync_state, del_flag, supplement_state ORDER BY n DESC;
SELECT '## recharge per month x adv.type (real recharges)' AS _;
SELECT DATE_FORMAT(r.create_time,'%Y-%m') ym, a.type, COUNT(*) n, ROUND(SUM(r.cash_recharge),0) cash_sum FROM dig_adveracoount_recharge r LEFT JOIN dig_advertising_account a ON a.id=r.adveraccount_id WHERE r.datatypes='0' GROUP BY ym, a.type ORDER BY ym, a.type;
SELECT '## recharge: source x tags x capital_type x credit_datatype' AS _;
SELECT source, tags, capital_type, credit_datatype, COUNT(*) n FROM dig_adveracoount_recharge GROUP BY source, tags, capital_type, credit_datatype ORDER BY n DESC;
SELECT '## cashrecharge: retype x approval_state x tag x del x invoice x recharge_flag' AS _;
SELECT retype, approval_state, tag, del_flag, invoice_flag, recharge_flag, COUNT(*) n, ROUND(SUM(money),0) money_sum, ROUND(AVG(TIMESTAMPDIFF(HOUR, create_time, complete_time)),1) avg_h FROM dig_cashrecharge GROUP BY retype, approval_state, tag, del_flag, invoice_flag, recharge_flag ORDER BY n DESC;
SELECT '## cashrecharge per month' AS _;
SELECT DATE_FORMAT(create_time,'%Y-%m') ym, COUNT(*) n, ROUND(SUM(money),0) money_sum FROM dig_cashrecharge GROUP BY ym ORDER BY ym;
SELECT '## transfer: approval x status x sync x conversion x source' AS _;
SELECT approval_state, status, sync_state, sync_state_in, transfer_conversion, source, del_flag, COUNT(*) n, ROUND(AVG(TIMESTAMPDIFF(HOUR, applicant_time, confirm_date)),1) avg_h FROM dig_transfer_account GROUP BY approval_state, status, sync_state, sync_state_in, transfer_conversion, source, del_flag ORDER BY n DESC;
SELECT '## transfer cross-customer' AS _;
SELECT SUM(customer_out_id=customer_in_id) same_cus, SUM(customer_out_id<>customer_in_id) cross_cus, SUM(customer_out_id IS NULL OR customer_in_id IS NULL) null_cus FROM dig_transfer_account;
SELECT '## return_coin: approval x status x refund_type x sync' AS _;
SELECT approval_state, status, refund_type, sync_state, del_flag, COUNT(*) n, ROUND(AVG(TIMESTAMPDIFF(HOUR, applicant_time, confirm_date)),1) avg_h FROM dig_return_coin GROUP BY approval_state, status, refund_type, sync_state, del_flag ORDER BY n DESC;
SELECT '## limit_apply: approval x datatype x credit_datatype x usable x state x timely' AS _;
SELECT approval_state, datatype, credit_datatype, usable, state, timely_pay, COUNT(*) n, ROUND(AVG(TIMESTAMPDIFF(HOUR, create_time, complete_time)),1) avg_h FROM dig_customer_limit_apply GROUP BY approval_state, datatype, credit_datatype, usable, state, timely_pay ORDER BY n DESC;
SELECT '## operratio approval_state x usable' AS _;
SELECT approval_state, usable, COUNT(*) n FROM dig_cus_operratio GROUP BY approval_state, usable;
SELECT '## statelog business_type x status' AS _;
SELECT business_type, status, COUNT(*) n, MIN(create_date) first_t, MAX(create_date) last_t FROM dig_bussiness_statelog GROUP BY business_type, status ORDER BY business_type, status;
SELECT '## statelog remarks top 30' AS _;
SELECT business_type, status, LEFT(remarks,60) rem, COUNT(*) n FROM dig_bussiness_statelog GROUP BY business_type, status, rem ORDER BY n DESC LIMIT 30;
SELECT '## approval process config' AS _;
SELECT p.id, p.no, p.type, p.role_id, p.role_name, p.dept_name, p.sort, p.limit_start, p.limit_end, p.del_flag FROM base_approval_process p ORDER BY p.no, p.sort;
SELECT '## approval process detail' AS _;
SELECT d.id, d.approval_id, d.type, d.role_id, d.role_name, d.dept_name, d.limit_start, d.limit_end, d.account_type, (d.user_id IS NOT NULL) has_user FROM base_approval_process_detail d ORDER BY d.approval_id, d.id;
SELECT '## sys_approval: type x state x role' AS _;
SELECT type, approval_state, role_name, COUNT(*) n FROM sys_approval GROUP BY type, approval_state, role_name ORDER BY type, n DESC;
SELECT '## consume per month: douyin vs other' AS _;
SELECT ym, SUM(src='dy') dy_rows, SUM(src='other') other_rows, ROUND(SUM(CASE WHEN src='dy' THEN spend END),0) dy_spend, ROUND(SUM(CASE WHEN src='other' THEN spend END),0) other_spend FROM (SELECT DATE_FORMAT(consume_date,'%Y-%m') ym, 'dy' src, actual_spend spend FROM dig_douyin_account_consume UNION ALL SELECT DATE_FORMAT(consume_date,'%Y-%m'), 'other', cost FROM dig_other_account_consume) t GROUP BY ym ORDER BY ym;
SELECT '## other_consume: business_type x supplier x agent' AS _;
SELECT business_type, business_type_name, supplier_id, agent_name, COUNT(*) n, ROUND(SUM(cost),0) cost_sum, MIN(consume_date) first_d, MAX(consume_date) last_d FROM dig_other_account_consume GROUP BY business_type, business_type_name, supplier_id, agent_name ORDER BY n DESC LIMIT 30;
SELECT '## douyin_consume: business_type x dy_agentId x agent x reporting_tag' AS _;
SELECT business_type, business_type_name, dy_agentId, agent_name, account_reporting_tag, COUNT(*) n, ROUND(SUM(actual_spend),0) spend_sum, MIN(consume_date) first_d, MAX(consume_date) last_d FROM dig_douyin_account_consume GROUP BY business_type, business_type_name, dy_agentId, agent_name, account_reporting_tag ORDER BY n DESC LIMIT 30;
SELECT '## which adv.type feeds which consume table' AS _;
SELECT 'dy' src, a.type, COUNT(DISTINCT c.account_id) accounts, COUNT(*) rows_n FROM dig_douyin_account_consume c JOIN dig_advertising_account a ON a.id=c.account_id GROUP BY a.type UNION ALL SELECT 'other', a.type, COUNT(DISTINCT c.account_id), COUNT(*) FROM dig_other_account_consume c JOIN dig_advertising_account a ON a.id=c.account_id GROUP BY a.type;
SELECT '## dy_developinfo (no secrets)' AS _;
SELECT id, agent_id, account_type, types, platformtype, (access_token IS NOT NULL AND access_token<>'') has_token, update_time FROM dig_dy_developinfo;
SELECT '## supplier list' AS _;
SELECT id, supplier_name, types, pay_type, account_type, suppliertype, dy_agentId, ks_agentId, del_flag, (main_wallet_id IS NOT NULL AND main_wallet_id<>'') has_main_wallet, last_consume_date, (apiprevfix IS NOT NULL AND apiprevfix<>'') has_api, returnratio FROM dig_supplier ORDER BY id;
SELECT '## customer x dept relation' AS _;
SELECT d.dept_name, COUNT(*) n FROM dig_customer_refdep r JOIN sys_dept d ON d.dept_id=r.dep_id GROUP BY d.dept_name ORDER BY n DESC;
SELECT '## cols: customer_tag / advertising_tag / external_orderno / customer_statement / customer_bill / wallet_bill / supplier_bill / edit_accountrecharge' AS _;
SELECT table_name, GROUP_CONCAT(CONCAT(column_name, IF(column_comment<>'', CONCAT('(',column_comment,')'), '')) ORDER BY ordinal_position SEPARATOR ' | ') cols FROM information_schema.columns WHERE table_schema='crm_xinhuo' AND table_name IN ('dig_customer_tag','dig_advertising_tag','dig_external_orderno','dig_customer_statement','dig_customer_bill','dig_customer_wallet_bill','dig_supplier_bill','dig_edit_accountrecharge','dig_customer_bill_split','dig_external_orderno','robot_send_record','dig_cus_operbalance') GROUP BY table_name;
SELECT '## customer_tag values' AS _;
SELECT * FROM dig_customer_tag LIMIT 0;
SELECT '## oper_log range' AS _;
SELECT MIN(oper_time) min_t, MAX(oper_time) max_t, COUNT(*) n, SUM(status=1) errors FROM sys_oper_log;
SELECT '## oper_log: title x business_type (last 6m)' AS _;
SELECT title, business_type, COUNT(*) n FROM sys_oper_log WHERE oper_time >= DATE_SUB(CURDATE(), INTERVAL 6 MONTH) GROUP BY title, business_type ORDER BY n DESC LIMIT 60;
SELECT '## oper_log: role x title (last 6m)' AS _;
SELECT r.role_name, l.title, COUNT(*) n FROM sys_oper_log l JOIN sys_user u ON u.user_name=l.oper_name JOIN sys_user_role ur ON ur.user_id=u.user_id JOIN sys_role r ON r.role_id=ur.role_id WHERE l.oper_time >= DATE_SUB(CURDATE(), INTERVAL 6 MONTH) GROUP BY r.role_name, l.title ORDER BY r.role_name, n DESC;
SELECT '## oper_log: top errors' AS _;
SELECT title, LEFT(error_msg,100) em, COUNT(*) n FROM sys_oper_log WHERE status=1 GROUP BY title, em ORDER BY n DESC LIMIT 20;
SELECT '## logins per month x role' AS _;
SELECT DATE_FORMAT(l.login_time,'%Y-%m') ym, r.role_name, COUNT(*) n, COUNT(DISTINCT l.user_name) users FROM sys_logininfor l JOIN sys_user u ON u.user_name=l.user_name JOIN sys_user_role ur ON ur.user_id=u.user_id JOIN sys_role r ON r.role_id=ur.role_id WHERE l.status='0' GROUP BY ym, r.role_name ORDER BY ym, n DESC;
