SELECT '## 同名客户跨模块重复（types 1 vs 10）' AS _;
SELECT COUNT(*) dup_names, SUM(cnt) rows_involved FROM (SELECT customer_name, COUNT(DISTINCT types) cnt FROM dig_customer WHERE del_flag='0' GROUP BY customer_name HAVING COUNT(DISTINCT types)>1) t;
SELECT '## 同名主体跨客户类型重复' AS _;
SELECT COUNT(*) dup_subjects FROM (SELECT cs.subject_name FROM dig_customer_subject cs JOIN dig_customer c ON c.id=cs.customer_id WHERE cs.del_flag='0' GROUP BY cs.subject_name HAVING COUNT(DISTINCT c.types)>1) t;
SELECT '## 同名主体在同一客户类型下重复' AS _;
SELECT COUNT(*) dup_subjects_same_type FROM (SELECT cs.subject_name, c.types FROM dig_customer_subject cs JOIN dig_customer c ON c.id=cs.customer_id WHERE cs.del_flag='0' GROUP BY cs.subject_name, c.types HAVING COUNT(*)>1) t;
SELECT '## 主体同时挂 102（自有端口）和 1001/1004（外转）账户' AS _;
SELECT COUNT(*) subjects_both FROM (SELECT subject_id FROM dig_advertising_account WHERE del_flag='0' GROUP BY subject_id HAVING SUM(type IN (100,102))>0 AND SUM(type IN (1001,1002,1003,1004))>0) t;
SELECT '## 多角色用户' AS _;
SELECT COUNT(*) users_multi_role FROM (SELECT user_id FROM sys_user_role GROUP BY user_id HAVING COUNT(*)>1) t;
SELECT '## 多角色组合' AS _;
SELECT GROUP_CONCAT(r.role_name ORDER BY r.role_name SEPARATOR ' + ') combo, COUNT(*) n FROM (SELECT user_id FROM sys_user_role GROUP BY user_id HAVING COUNT(*)>1) m JOIN sys_user_role ur ON ur.user_id=m.user_id JOIN sys_role r ON r.role_id=ur.role_id GROUP BY m.user_id ORDER BY n DESC;
SELECT '## account_infojson 样例（无个人信息，账户类型汇总）' AS _;
SELECT LEFT(account_infojson,160) sample, COUNT(*) n FROM dig_customer_subject GROUP BY sample ORDER BY n DESC LIMIT 6;
SELECT '## 客户标签分布' AS _;
SELECT tag_name, COUNT(*) n FROM dig_customer_tag GROUP BY tag_name ORDER BY n DESC;
SELECT '## 账户标签分布' AS _;
SELECT tag_name, COUNT(*) n FROM dig_advertising_tag GROUP BY tag_name ORDER BY n DESC;
SELECT '## 每个客户的主体数/店铺数/账户数 分布' AS _;
SELECT CASE WHEN a.n>=100 THEN '100+' WHEN a.n>=20 THEN '20-99' WHEN a.n>=5 THEN '5-19' WHEN a.n>=1 THEN '1-4' ELSE '0' END bucket, COUNT(*) customers FROM (SELECT c.id, COUNT(aa.id) n FROM dig_customer c LEFT JOIN dig_advertising_account aa ON aa.customer_id=c.id AND aa.del_flag='0' WHERE c.del_flag='0' GROUP BY c.id) a GROUP BY bucket ORDER BY MIN(a.n);
SELECT '## 主体->店铺->账户 层级利用：店铺与主体同名比例' AS _;
SELECT SUM(s.shop_name=cs.subject_name) same_name, COUNT(*) total FROM dig_shop s JOIN dig_customer_subject cs ON cs.id=s.subject_id WHERE s.del_flag='0';
SELECT '## 微信机器人群绑定数 / 客户钱包数' AS _;
SELECT (SELECT COUNT(*) FROM dig_robot_ex) robot_groups, (SELECT COUNT(*) FROM dig_customer_wallet WHERE del_flag='0') wallets, (SELECT COUNT(DISTINCT customer_id) FROM dig_customer_wallet WHERE del_flag='0') customers_with_wallet;
SELECT '## 客户钱包名称分布' AS _;
SELECT a_name, COUNT(*) n FROM dig_customer_wallet WHERE del_flag='0' GROUP BY a_name ORDER BY n DESC LIMIT 10;
SELECT '## 对账单 生成/结算 情况' AS _;
SELECT credit_datatype, is_completed, COUNT(*) n, MIN(generate_date) first_d, MAX(generate_date) last_d FROM dig_customer_statement GROUP BY credit_datatype, is_completed;
SELECT '## 开户申请：申请人角色分布' AS _;
SELECT r.role_name, COUNT(*) n FROM dig_accountopen_apply a JOIN sys_user_role ur ON ur.user_id=a.create_by JOIN sys_role r ON r.role_id=ur.role_id GROUP BY r.role_name ORDER BY n DESC;
SELECT '## 开户申请：处理人角色分布' AS _;
SELECT r.role_name, COUNT(*) n FROM dig_accountopen_apply a JOIN sys_user_role ur ON ur.user_id=a.reply_userid JOIN sys_role r ON r.role_id=ur.role_id GROUP BY r.role_name ORDER BY n DESC;
SELECT '## 广告账户：创建人角色分布' AS _;
SELECT r.role_name, COUNT(*) n FROM dig_advertising_account a JOIN sys_user_role ur ON ur.user_id=a.create_by JOIN sys_role r ON r.role_id=ur.role_id WHERE a.del_flag='0' GROUP BY r.role_name ORDER BY n DESC;
SELECT '## 广告账户：remark 分布（来源）' AS _;
SELECT remark, COUNT(*) n FROM dig_advertising_account WHERE del_flag='0' GROUP BY remark ORDER BY n DESC;
